version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/usr/src/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"
    deploy:
     replicas: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "3000:3000"
    command: 'yarn start'
    deploy:
      replicas: 2

  db:
    image: "postgres"
    deploy:
      replicas: 1